apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/zregvart/golden-container?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main"
  labels:
    appstudio.openshift.io/application: golden-container
    appstudio.openshift.io/component: golden-container
    pipelines.appstudio.openshift.io/type: build
  name: golden-container-on-push
  namespace: zregvart-tenant
spec:
  params:
    - name: dockerfile
      value: Containerfile
    - name: git-url
      value: '{{repo_url}}'
    - name: output-image
      value: quay.io/redhat-user-workloads-stage/zregvart-tenant/golden-container/golden-container:{{revision}}
    - name: path-context
      value: .
    - name: revision
      value: '{{revision}}'
    - name: build-source-image
      value: true
  pipelineRef:
    params:
      - name: bundle
        value: quay.io/zregvart_redhat/pipeline-docker-build-rhtap@sha256:e90889e190ceb2d77db4678f5b1fd315d14cf714edb4a8393920bc06378e9a93
      - name: name
        value: docker-build-rhtap
      - name: kind
        value: pipeline
    resolver: bundles
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
