apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/zregvart/golden-container?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main"
  labels:
    appstudio.openshift.io/application: golden-container
    appstudio.openshift.io/component: golden-container
    pipelines.appstudio.openshift.io/type: build
  name: golden-container-on-push
  namespace: zregvart-tenant
spec:
  params:
  - name: dockerfile
    value: Containerfile
  - name: git-url
    value: '{{repo_url}}'
  - name: output-image
    value: quay.io/redhat-user-workloads-stage/zregvart-tenant/golden-container/golden-container:{{revision}}
  - name: path-context
    value: .
  - name: revision
    value: '{{revision}}'
  - name: hermetic
    value: 'true'
  pipelineRef:
    resolver: bundles
    params:
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/pipeline-docker-build:devel@sha256:af05604be7360375a1862a5c532c4783eaf971d0f72be75fa73e6643deac344a
      - name: name
        value: docker-build
      - name: kind
        value: pipeline
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'