---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/enterprise-contract/golden-container?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: golden-container
    appstudio.openshift.io/component: golden-container
    pipelines.appstudio.openshift.io/type: build
  name: golden-container-on-tag-latest
  namespace: rhtap-contract-tenant
spec:
  params:
    - name: revision
      value: '{{revision}}'
  pipelineSpec:
    params:
      - name: revision
    tasks:
      - name: tag-with-latest
        params:
          - name: revision
            value: '$(params.revision)'
        taskSpec:
          params:
            - name: revision
          steps:
            - name: tag-with-latest
              image: registry.access.redhat.com/ubi9/skopeo:latest@sha256:da65193188b934b73c39bf225b778e7e3b4ca6f775b91a9e754b56e8fd47e988
              script: |
                #!/usr/bin/env bash
                SRC_REF=quay.io/redhat-appstudio/ec-golden-image:$(params.revision)
                TARGET_REF=quay.io/redhat-appstudio/ec-golden-image:latest

                retries=0
                while ! skopeo inspect docker://${SRC_REF} >/dev/null 2>&1; do
                  (( retries++ ))
                  if (( retries > 200 )); then
                    echo
                    echo ${SRC_REF} has not been pushed within 10 min
                    exit 1
                  fi
                  echo -n .
                  sleep 3
                done
                echo
                echo ${SRC_REF} has been pushed, copying to ${TARGET_REF}

                skopeo copy docker://${SRC_REF} docker://${TARGET_REF}
